connect to svc

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,25 +31,6 @@ jobs:
         ports:
           - "8000:8000"
         options: --health-cmd="curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8000 | grep -q 400 || exit 1" --health-interval=1s --health-timeout=2s --health-retries=10
-
-  test:
-    runs-on: ubuntu-latest
-    needs: start-dynamodb
-    env:
-      AWS_PAGER: ""
-      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
-      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
-      AWS_REGION: local
-      DYNAMODB_TABLE: stateful_aws_api_tasks
-      DYNAMODB_ENDPOINT: http://host.docker.internal:8000
-
-    # services:
-    #   dynamodb-local:
-    #     image: "amazon/dynamodb-local:latest"
-    #     ports:
-    #       - "8000:8000"
-    #     options: --health-cmd="curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8000 | grep -q 400 || exit 1" --health-interval=1s --health-timeout=2s --health-retries=10
-    
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -66,13 +47,66 @@ jobs:
           #   amazon/dynamodb-local
           # sleep 5
           aws dynamodb list-tables --region local --endpoint-url http://localhost:8000
-          echo lols
-          # docker run --rm \
+          echo svc
+
+  test:
+    runs-on: ubuntu-latest
+    needs: start-dynamodb
+    env:
+      AWS_PAGER: ""
+      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
+      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
+      AWS_REGION: local
+      DYNAMODB_TABLE: stateful_aws_api_tasks
+      DYNAMODB_ENDPOINT: http://host.docker.internal:8000
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: run db
+        run: |
+          # cp ${GITHUB_WORKSPACE}/.env.example ${GITHUB_WORKSPACE}/.env
+          # docker run -d -p 8000:8000 \
           #   -e AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE \
           #   -e AWS_SECRET_ACCESS_KEY=DUMMYIDEXAMPLE \
           #   -e AWS_DEFAULT_REGION=local \
-          #   amazon/aws-cli \
-          #   dynamodb list-tables --endpoint-url http://0.0.0.0:8000
+          #   amazon/dynamodb-local
+          # sleep 5
+          aws dynamodb list-tables --region local --endpoint-url http://localhost:8000
+          echo test
+
+    # services:
+    #   dynamodb-local:
+    #     image: "amazon/dynamodb-local:latest"
+    #     ports:
+    #       - "8000:8000"
+    #     options: --health-cmd="curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8000 | grep -q 400 || exit 1" --health-interval=1s --health-timeout=2s --health-retries=10
+    
+    # steps:
+    #   - name: checkout
+    #     uses: actions/checkout@v4
+    #     with:
+    #       fetch-depth: 0
+
+    #   - name: run db
+    #     run: |
+    #       # cp ${GITHUB_WORKSPACE}/.env.example ${GITHUB_WORKSPACE}/.env
+    #       # docker run -d -p 8000:8000 \
+    #       #   -e AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE \
+    #       #   -e AWS_SECRET_ACCESS_KEY=DUMMYIDEXAMPLE \
+    #       #   -e AWS_DEFAULT_REGION=local \
+    #       #   amazon/dynamodb-local
+    #       # sleep 5
+    #       aws dynamodb list-tables --region local --endpoint-url http://localhost:8000
+    #       echo lols
+    #       # docker run --rm \
+    #       #   -e AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE \
+    #       #   -e AWS_SECRET_ACCESS_KEY=DUMMYIDEXAMPLE \
+    #       #   -e AWS_DEFAULT_REGION=local \
+    #       #   amazon/aws-cli \
+    #       #   dynamodb list-tables --endpoint-url http://0.0.0.0:8000
 
 
       # - name: create db
